title: danieljw.net
description: A collection of things that I've worked on and interesting projects that you may find useful.
author: Daniel W
language: en
permalink: posts/:post_title/

theme: cactus
theme_config:
  projects_url:       http://github.com/djw4
  colorscheme:        white
  nav:                { home: /, projects: https://github.com/djw4}
  gravatar:           { email: dw@danieljw.net }
  posts_overview:     { show_all_posts: true }
  social_links:       { github: http://github.com/djw4, linkedin: https://www.linkedin.com/in/djw1 }
  disqus:             { enabled: false }
  google_analytics:   { enabled: false }
  baidu_analytics:    { enabled: false }
  rss: false

# deploy:
#   type: ftpsync
#   host: remote.danieljw.net
#   user: <user>
#   pass: <password>
#   remote: [/usr/share/caddy]
#   port: [21]
#   ignore: [ignore]
#   connections: [5]
#   verbose: [true]
#   # https://hexo.io/docs/deployment#FTPSync
