version: "3"
services:
  hexo:
    # image: ipple1986/hexo
    build: .
    image: hexo
    deploy:
      restart_policy:
        condition: unless-stopped
      replicas: 1
      resources:
       limits:
         cpus: "0.25"
         memory: 256M
    ports:
      - "4000:4000"
    volumes:
      - './_config.yml:${HEXO_PATH}/_config.yml'
      - "./themes:${HEXO_PATH}/themes"
      - './static:${HEXO_PATH}/source/static'
      - './public:${HEXO_PATH}/public:rw'
      - './posts:${HEXO_PATH}/source/_posts'
    networks:
      - dnet  

networks: 
  dnet:
